//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Detail
    {
        public int AccountId { get; set; }
        public int PointId { get; set; }
        public Nullable<double> Total { get; set; }
        public bool Active { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Point Point { get; set; }
    }
}
