//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manga_Detail
    {
        public int AccountId { get; set; }
        public int MangaId { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> StatusActive { get; set; }
        public Nullable<int> Type { get; set; }
        public string Language { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Manga Manga { get; set; }
        public virtual Role Role { get; set; }
    }
}
