//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointHistory
    {
        public int HistoryId { get; set; }
        public Nullable<System.DateTime> ToDay { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<double> DTPoint { get; set; }
        public Nullable<double> QLBDPoint { get; set; }
        public Nullable<double> QLTPoint { get; set; }
        public Nullable<double> UPCLEARPoint { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> MangaId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
