//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Text
    {
        public int TextId { get; set; }
        public string TextContent { get; set; }
        public string ColorText { get; set; }
        public string ColorOutline { get; set; }
        public bool Bold { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> Allow { get; set; }
        public int TranslationId { get; set; }
        public int AccountId { get; set; }
        public int TextBoxId { get; set; }
        public int FontId { get; set; }
        public int FontSize { get; set; }
        public bool Italic { get; set; }
    
        public virtual Font Font { get; set; }
        public virtual TextBox TextBox { get; set; }
        public virtual Translation Translation { get; set; }
        public virtual Account Account { get; set; }
    }
}
