//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Text
    {
        public int TextId { get; set; }
        public string TextContent { get; set; }
        public string ColorText { get; set; }
        public string ColorOutline { get; set; }
        public Nullable<int> Bold { get; set; }
        public Nullable<int> StatusActive { get; set; }
        public Nullable<int> StatusAllow { get; set; }
        public Nullable<int> TranslationId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> TextBoxId { get; set; }
        public Nullable<int> FontId { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string Italic { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Font Font { get; set; }
        public virtual TextBox TextBox { get; set; }
        public virtual Translation Translation { get; set; }
    }
}
