//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chapter()
        {
            this.Pages = new HashSet<Page>();
        }
    
        public int ChapterId { get; set; }
        public string FullName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<int> ViewNumber { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> StatusActive { get; set; }
        public Nullable<int> MangaId { get; set; }
    
        public virtual Manga Manga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Pages { get; set; }
    }
}
